frr version 10.6
frr defaults traditional
hostname upstream
service integrated-vtysh-config
!
interface lo
 ip address 8.8.8.8/32
!
interface eth1
 ip address 10.0.0.1/30
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 10.255.0.1
 neighbor 10.0.0.2 remote-as 65001
 address-family ipv4 unicast
  network 8.8.8.8/32
  neighbor 10.0.0.2 activate
 exit-address-family
!
ip route 0.0.0.0/0 Null0
ip route 8.8.8.8/32 Null0
!
line vty
