[modules]
pppoe
ippool
log_file
auth_chap_md5
chap-secrets

[core]
thread-count=2

[ppp]
mtu=1492
mru=1492
verbose=1

[pppoe]
interface=eth2
ac-name=clab-isp
verbose=1

[chap-secrets]
chap-secrets=/etc/ppp/chap-secrets

[ip-pool]
gw-ip-address=100.64.0.1
100.64.0.2-100.64.0.254

[dns]
dns1=1.1.1.1
dns2=8.8.8.8

[log]
log-file=/var/log/accel-ppp.log
log-emerg=/var/log/accel-ppp.log

[cli]
tcp=127.0.0.1:2001
