frr version 10.6
frr defaults traditional
hostname bng
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.1.2/30
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.3
 network 10.0.1.0/30 area 0
 network 100.64.0.0/24 area 0
 redistribute connected
!
line vty
